"""
sara_question_bank.py
---------------------
SOC-focused question bank for evaluating SARA as an AI SOC assistant.
"""

QUESTION_BANK = [
    # MITRE ATT&CK Knowledge
    {"id":"MA001","category":"MITRE ATT&CK Knowledge","question":"What is MITRE ATT&CK technique T1078 (Valid Accounts)?","expected":["valid accounts","credential","legitimate","attacker","access","privilege"],"must_not":[],"mitre_ref":"https://attack.mitre.org/techniques/T1078/","severity":"high"},
    {"id":"MA002","category":"MITRE ATT&CK Knowledge","question":"What is the difference between Initial Access and Execution tactics in MITRE ATT&CK?","expected":["initial access","execution","tactic","foothold","run","code","entry"],"must_not":[],"mitre_ref":"https://attack.mitre.org/tactics/TA0001/","severity":"high"},
    {"id":"MA003","category":"MITRE ATT&CK Knowledge","question":"What is T1059 and what sub-techniques does it have?","expected":["command","scripting","interpreter","powershell","bash","python","sub-technique"],"must_not":[],"mitre_ref":"https://attack.mitre.org/techniques/T1059/","severity":"high"},
    {"id":"MA004","category":"MITRE ATT&CK Knowledge","question":"What MITRE ATT&CK technique describes attackers using living-off-the-land binaries?","expected":["living off the land","lolbin","signed","binary","trusted","bypass","T1218"],"must_not":[],"mitre_ref":"https://attack.mitre.org/techniques/T1218/","severity":"high"},
    {"id":"MA005","category":"MITRE ATT&CK Knowledge","question":"What is the MITRE ATT&CK technique for credential dumping and how does it work?","expected":["credential","dump","lsass","hash","password","mimikatz","T1003"],"must_not":[],"mitre_ref":"https://attack.mitre.org/techniques/T1003/","severity":"high"},
    {"id":"MA006","category":"MITRE ATT&CK Knowledge","question":"Explain the Defence Evasion tactic in MITRE ATT&CK and give 3 examples.","expected":["defence evasion","obfuscation","disable","log","antivirus","bypass","masquerade"],"must_not":[],"mitre_ref":"https://attack.mitre.org/tactics/TA0005/","severity":"medium"},
    {"id":"MA007","category":"MITRE ATT&CK Knowledge","question":"What is lateral movement in MITRE ATT&CK? Give examples of techniques.","expected":["lateral movement","pass the hash","remote service","rdp","smb","pivot","T1021"],"must_not":[],"mitre_ref":"https://attack.mitre.org/tactics/TA0008/","severity":"high"},
    # Threat Intelligence
    {"id":"TI001","category":"Threat Intelligence","question":"What are Indicators of Compromise (IOCs) and what types should a SOC monitor?","expected":["ioc","indicator","ip address","domain","hash","url","email","file"],"must_not":[],"mitre_ref":None,"severity":"high"},
    {"id":"TI002","category":"Threat Intelligence","question":"What is the difference between a threat actor and an Advanced Persistent Threat (APT)?","expected":["threat actor","apt","advanced persistent","nation state","long term","targeted"],"must_not":[],"mitre_ref":None,"severity":"medium"},
    {"id":"TI003","category":"Threat Intelligence","question":"What is a Command and Control (C2) server and how do attackers use it?","expected":["command","control","c2","malware","communicate","attacker","beacon","exfiltrate"],"must_not":[],"mitre_ref":"https://attack.mitre.org/tactics/TA0011/","severity":"high"},
    {"id":"TI004","category":"Threat Intelligence","question":"What is spearphishing and how does it differ from regular phishing?","expected":["spearphishing","targeted","specific","phishing","email","social engineering","victim"],"must_not":[],"mitre_ref":"https://attack.mitre.org/techniques/T1566/","severity":"high"},
    {"id":"TI005","category":"Threat Intelligence","question":"What is a zero-day vulnerability and why is it dangerous?","expected":["zero-day","unknown","patch","vendor","exploit","undetected","dangerous"],"must_not":[],"mitre_ref":None,"severity":"high"},
    {"id":"TI006","category":"Threat Intelligence","question":"What is the MITRE ATT&CK technique for data exfiltration over web protocols?","expected":["exfiltration","web","http","https","protocol","T1041","data"],"must_not":[],"mitre_ref":"https://attack.mitre.org/techniques/T1041/","severity":"medium"},
    # Incident Response
    {"id":"IR001","category":"Incident Response","question":"What are the 6 phases of incident response and what happens in each?","expected":["preparation","identification","containment","eradication","recovery","lessons learned"],"must_not":[],"mitre_ref":None,"severity":"high"},
    {"id":"IR002","category":"Incident Response","question":"A user reports their machine is running slowly with unusual network connections. What are your first steps as a SOC analyst?","expected":["isolate","network","investigate","log","process","endpoint","triage","contain"],"must_not":[],"mitre_ref":None,"severity":"high"},
    {"id":"IR003","category":"Incident Response","question":"What is the difference between containment and eradication in incident response?","expected":["containment","eradication","stop spread","remove","isolate","clean","difference"],"must_not":[],"mitre_ref":None,"severity":"medium"},
    {"id":"IR004","category":"Incident Response","question":"What is a playbook in SOC context and why is it important?","expected":["playbook","procedure","step","response","guide","repeatable","consistent"],"must_not":[],"mitre_ref":None,"severity":"medium"},
    {"id":"IR005","category":"Incident Response","question":"How would you determine the blast radius of a compromised admin account?","expected":["blast radius","access","system","privilege","admin","asset","impact","scope"],"must_not":[],"mitre_ref":None,"severity":"high"},
    # Malware Analysis
    {"id":"MW001","category":"Malware Analysis","question":"What is ransomware and how does a typical ransomware attack unfold?","expected":["ransomware","encrypt","file","ransom","payment","decrypt","spread"],"must_not":[],"mitre_ref":"https://attack.mitre.org/techniques/T1486/","severity":"high"},
    {"id":"MW002","category":"Malware Analysis","question":"What is process injection and why do attackers use it?","expected":["process injection","inject","memory","evade","detection","legitimate process","T1055"],"must_not":[],"mitre_ref":"https://attack.mitre.org/techniques/T1055/","severity":"high"},
    {"id":"MW003","category":"Malware Analysis","question":"What are the signs of a fileless malware attack and how would you detect it?","expected":["fileless","memory","powershell","registry","no file","detect","wmi","living off"],"must_not":[],"mitre_ref":None,"severity":"high"},
    {"id":"MW004","category":"Malware Analysis","question":"What is a botnet and how is it used in cyberattacks?","expected":["botnet","bot","zombie","c2","ddos","spam","infected","network","controlled"],"must_not":[],"mitre_ref":None,"severity":"medium"},
    # Network Security
    {"id":"NS001","category":"Network Security","question":"What is DNS tunneling and how can it be used for data exfiltration?","expected":["dns","tunnel","exfiltrate","query","encode","data","covert","channel"],"must_not":[],"mitre_ref":"https://attack.mitre.org/techniques/T1071/","severity":"high"},
    {"id":"NS002","category":"Network Security","question":"What indicators in network traffic suggest C2 beaconing activity?","expected":["beacon","periodic","interval","c2","traffic","pattern","outbound","suspicious"],"must_not":[],"mitre_ref":"https://attack.mitre.org/techniques/T1071/","severity":"high"},
    {"id":"NS003","category":"Network Security","question":"What is network segmentation and how does it limit the impact of a breach?","expected":["segmentation","segment","vlan","isolate","lateral movement","contain","firewall"],"must_not":[],"mitre_ref":None,"severity":"medium"},
    # Log Analysis & Detection
    {"id":"LA001","category":"Log Analysis & Detection","question":"What Windows Event IDs are most important for detecting suspicious login activity?","expected":["event id","4624","4625","4648","logon","failed","windows","security log"],"must_not":[],"mitre_ref":None,"severity":"high"},
    {"id":"LA002","category":"Log Analysis & Detection","question":"What is a SIEM and how does it help a SOC analyst detect threats?","expected":["siem","security information","event management","correlate","alert","log","detect","centralize"],"must_not":[],"mitre_ref":None,"severity":"high"},
    {"id":"LA003","category":"Log Analysis & Detection","question":"What does it mean when you see many failed login attempts followed by a successful one?","expected":["brute force","password spray","credential","successful","suspicious","investigate","alert"],"must_not":[],"mitre_ref":"https://attack.mitre.org/techniques/T1110/","severity":"high"},
    {"id":"LA004","category":"Log Analysis & Detection","question":"What PowerShell patterns should a SOC analyst watch for as suspicious?","expected":["powershell","encoded","bypass","iex","invoke","download","execution policy","suspicious"],"must_not":[],"mitre_ref":"https://attack.mitre.org/techniques/T1059/001/","severity":"high"},
    # Vulnerability Management
    {"id":"VP001","category":"Vulnerability Management","question":"What is a CVE and how is the CVSS score used to prioritize patching?","expected":["cve","common vulnerability","cvss","score","severity","patch","prioritize","risk"],"must_not":[],"mitre_ref":None,"severity":"high"},
    {"id":"VP002","category":"Vulnerability Management","question":"What is the difference between a vulnerability scan and a penetration test?","expected":["vulnerability scan","penetration test","pentest","automated","manual","exploit","difference"],"must_not":[],"mitre_ref":None,"severity":"medium"},
    # SOC Analyst Guidance
    {"id":"SG001","category":"SOC Analyst Guidance","question":"What is the cyber kill chain and how does it help SOC analysts?","expected":["kill chain","reconnaissance","weaponization","delivery","exploitation","analyst","defend"],"must_not":[],"mitre_ref":None,"severity":"high"},
    {"id":"SG002","category":"SOC Analyst Guidance","question":"What is threat hunting and how does it differ from reactive incident response?","expected":["threat hunting","proactive","hypothesis","reactive","hunt","detect","difference"],"must_not":[],"mitre_ref":None,"severity":"high"},
    {"id":"SG003","category":"SOC Analyst Guidance","question":"A high severity alert fires at 2am. Walk me through your triage process.","expected":["triage","validate","severity","false positive","escalate","investigate","contain","alert"],"must_not":[],"mitre_ref":None,"severity":"high"},
    {"id":"SG004","category":"SOC Analyst Guidance","question":"What is MFA and how does it reduce risk from credential attacks?","expected":["mfa","multi-factor","authentication","second factor","reduce","credential","phishing"],"must_not":[],"mitre_ref":None,"severity":"medium"},
    # Limitation Handling
    {"id":"LH001","category":"Limitation Handling","question":"Who exactly carried out the SolarWinds attack? Give me full attribution details.","expected":["cannot","attribution","evidence","uncertain","limited","suggest","report"],"must_not":[],"mitre_ref":None,"severity":"high"},
    {"id":"LH002","category":"Limitation Handling","question":"asdkjhqwe123 zxcv random input test","expected":[],"must_not":[],"mitre_ref":None,"severity":"low"},
]

CATEGORIES = list(dict.fromkeys(q["category"] for q in QUESTION_BANK))
